apiVersion: controller.kubeslice.io/v1alpha1
kind: SliceConfig
metadata:
  name: rohan
spec:
  sliceType: Application
  maxClusters: 14
  clusters:
    - worker-1
  overlayNetworkDeploymentMode: no-network
  namespaceIsolationProfile:
    applicationNamespaces:
      - clusters:
          - worker-1
        namespace: test
